node-0:
  - node-1
  - node-2
  - node-3
  - node-4
node-1:
  - node-5
  - node-6
  - node-7
  - node-8
node-2:
  - node-9
  - node-10
  - node-11
  - node-12
node-3:
  - node-13
  - node-14
  - node-15
  - node-16
node-4:
  - node-17
  - node-18
  - node-19
  - node-20
node-5:
  - node-21
  - node-22
  - node-23
  - node-24
node-6:
  - node-25
  - node-26
  - node-27
  - node-28
node-7:
  - node-29
  - node-30
  - node-31
  - node-32
node-8:
  - node-33
  - node-34
  - node-35
  - node-36
node-9:
  - node-37
  - node-38
  - node-39
  - node-40
node-10:
  - node-41
  - node-42
  - node-43
  - node-44
node-11:
  - node-45
  - node-46
  - node-47
  - node-48
node-12:
  - node-49